# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0002_auto_20150815_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCigarShop',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('template_app.cigarshop',),
        ),
    ]
