# vagrant plugin install vagrant-puppet-install
# vagrant plugin install vagrant-vbguest
# vagrant init centos/7;

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.network :forwarded_port, guest: 8000, host: 8000
    config.vm.network :forwarded_port, guest: 80, host: 8888
    config.puppet_install.puppet_version = :latest
    config.vm.provision :shell do |shell|
        shell.inline = "mkdir -p /etc/puppet/modules;
                        puppet module install puppetlabs-stdlib;"
    end
    config.vm.provision "puppet" do |puppet|
       #puppet.options = "--verbose --debug"
    end
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
end