# vagrant plugin install vagrant-puppet-install
# vagrant plugin install vagrant-vbguest
# vagrant init centos/7;
# ulimit -n 4048


Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.network :forwarded_port, guest: 8000, host: 8000
    config.vm.network :forwarded_port, guest: 80, host: 8888
    config.vm.network :forwarded_port, guest: 5432, host: 5432
    config.vm.network :forwarded_port, guest: 9876, host: 9876
    
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
    
    config.puppet_install.puppet_version = :latest
    config.vm.provision :shell do |shell|
        shell.inline = "mkdir -p /opt/puppetlabs/puppet/modules;
                        puppet module install stahnma-epel --target-dir /opt/puppetlabs/puppet/modules;
                        puppet module install m0byd1ck-repoforge --target-dir /opt/puppetlabs/puppet/modules;
                        puppet module install puppetlabs-postgresql --target-dir /opt/puppetlabs/puppet/modules;
                        puppet module install stankevich-python --target-dir /opt/puppetlabs/puppet/modules;
                        puppet module install puppetlabs-vcsrepo --target-dir /opt/puppetlabs/puppet/modules;
                        puppet module install jfryman-nginx --target-dir /opt/puppetlabs/puppet/modules;
                        puppet module install saz-sudo --target-dir /opt/puppetlabs/puppet/modules;
                        puppet module install jfryman-selinux --target-dir /opt/puppetlabs/puppet/modules;"
    end
    config.vm.provision "puppet" do |puppet|
        puppet.options = "--verbose --debug"
        puppet.environment_path = "environments"
        puppet.environment = "default"
    end
    
    config.vm.network "private_network", ip: "192.168.50.4"
end